import 'package:get/get.dart';

class Language extends Translations{
  @override
  Map<String, Map<String, String>> get keys=>{
    "en_US":{
      "welcome_message":"Welcome to the stores application",
      "tittle_onboarding1":"Choose from a large number of supply stores",
      "text_onboarding1":"Online fashion shopping marketplace application ranging from \nclothes, pants, skirts, shoes, sandals, to accessories from \nvarious brands.",
      "tittle_onboarding2":"Book an appointment for your wedding day",
      "text_onboarding2":"We make it easy for you to shop for your fashion needs from various brands online through our application without having\n to come directly to the store.",
      "onboarding_button":"Next",
      "login_text":"Get Started",
      "login_tff":"Phone Number",
      "login_tff2":"Password",
      "login_button":"Log in",
      "home_order":"Orders",
      "home_service":"Services",
      "home_products":"Products",
      "home_income":"Income",
      "home_evaluation":"Evaluation",
      "home_mystore":"My Store",
      "bnb_home":"Home",
      "bnb_store":"Stores",
      "bnb_mybooking":"My Booking",
      "bnb_chat":"Chat",
      "my_store":"My Store",
      "store_name":"Store Name",
      "tab_service":"Services",
      "tab_product":"Product",
      "tab_about":"About",
      "service_card":"Services Name",
      "product_card":"Product Name",
      "about_store_name":"Store Name",
      "enter_about_name":"Enter Your Store Name",
      "about_store":"About this store",
      "about_store_data":"Golend gate is provider water",
      "business_hours":"Business Hours",
      "about_photo":"Photo",
      "about_company":"Company Information",
      "about_company_info":"Enter Company Info....",
      "about_contact":"Contact Us",
      "order_screen":"Orders",
      "order_wedding":"Wedding day preparation",
      "order_pending":"Pending",
      "order_progress":"Progress",
      "order_complete":"Complete",
      "chat_button":"Chat",
      "done_button":"Done",
      "pending_button":"Confirm order",
      "chat_screen":"Chat",
      "chat_message":"Messages",
      "chat_see_all":"See all",
      "notification_screen":"Notification",
    },
    "ur_Pk":{
      "welcome_message":"اسٹورز کی درخواست میں خوش آمدید",
      "tittle_onboarding1":"سپلائی اسٹورز کی ایک بڑی تعداد میں سے انتخاب کریں۔",
      "text_onboarding1":"آن لائن فیشن شاپنگ مارکیٹ پلیس ایپلی کیشن \nکپڑے، پتلون، سکرٹ، جوتے، سینڈل سے لے کر مختلف برانڈز کے لوازمات تک۔",
      "tittle_onboarding2":"اپنی شادی کے دن کے لیے ملاقات کا وقت بک کرو",
      "text_onboarding2":"ہم آپ کے لیے براہ راست اسٹور پر آنے کے بغیر اپنی ایپلیکیشن کے ذریعے مختلف برانڈز سے اپنی فیشن کی ضروریات کو آن لائن خریدنا آسان بناتے ہیں۔",
      "onboarding_button":"اگلا",
      "login_text":"شروع کریں",
      "login_tff":"فون نمبر",
      "login_tff2":"پاس ورڈ",
      "login_button":"لاگ ان کریں۔",
      "home_order":"احکامات",
      "home_service":"خدمات",
      "home_products":"مصنوعات",
      "home_income":"آمدنی",
      "home_evaluation":"تشخیص",
      "home_mystore":"میرا اسٹور",
      "bnb_home":"گھر",
      "bnb_store":"اسٹورز",
      "bnb_mybooking":"میری بکنگ",
      "bnb_chat":"گپ شپ",
      "my_store":"میرا اسٹور",
      "store_name":"اسٹور کا نام",
      "tab_service":"خدمات",
      "tab_product":"پروڈکٹ",
      "tab_about":"کے بارے میں",
      "service_card":"خدمات کا نام",
      "product_card":"پروڈکٹ کا نام",
      "about_store_name":"اسٹور کا نام",
      "enter_about_name":"اپنے اسٹور کا نام درج کریں۔",
      "about_store":"اس اسٹور کے بارے میں",
      "about_store_data":"گولینڈ گیٹ پانی فراہم کرنے والا ہے۔",
      "business_hours":"کاروباری اوقات",
      "about_photo":"تصویر",
      "about_company":"کمپنی کی معلومات",
      "about_company_info":"کمپنی کی معلومات درج کریں...",
      "about_contact":"ہم سے رابطہ کریں۔",
      "order_screen":"احکامات",
      "order_wedding":"شادی کے دن کی تیاری",
      "order_pending":"زیر التواء",
      "order_progress":"پیش رفت",
      "order_complete":"مکمل",
      "chat_button":"گپ شپ",
      "done_button":"ہو گیا",
      "pending_button":"آرڈر کی تصدیق کریں۔",
      "chat_screen":"گپ شپ",
      "chat_message":"پیغامات",
      "chat_see_all":"سب دیکھیں",
      "notification_screen":"اطلاع",
    }
  };

}